# Generated by Django 5.0.1 on 2024-03-02 18:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Size', models.IntegerField()),
                ('Weight', models.IntegerField()),
                ('Sweetness', models.IntegerField()),
                ('Crunchiness', models.IntegerField()),
                ('Juiciness', models.IntegerField()),
                ('Ripeness', models.IntegerField()),
                ('Acidity', models.IntegerField()),
                ('time_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('PredictionResult', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
